version: "3.4"

services:
  web:
    hostname: palarm-web
    # ports:
    #   - 666:666
    build:
      context: web/
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_HOST=https://palarm.myngz.com
    restart: always
    networks:
      - ngix-manager_default
  server:
    hostname: palarm-server
    # ports:
    #   - 5000:5000
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    networks:
      - ngix-manager_default

networks:
  ngix-manager_default:
    external: false
    name: ngix-manager_default
